/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alexa
 */
public class cautare_carti extends javax.swing.JFrame {

    /**
     * Creates new form cautare_carti
     */
    public cautare_carti() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("CNP");
        if(jRadioButton1.isSelected())
        jRadioButton2.setSelected(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Nume");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cauta");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cautarea se face in functie de :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("State : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText(" ");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Inapoi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  private static final String DB_DRIVER = "oracle.jdbc.driver.OracleDriver";
	private static final String DB_CONNECTION = "jdbc:mysql://localhost:3306/test";
	private static final String DB_USER = "root";
	private static final String DB_PASSWORD = "";
        private int i=0;
    private void set_button()
    {
        if(jRadioButton1.isSelected())   
        jRadioButton2.setSelected(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        this.setSize(645, 500);

    Connection dbConnection = null;
		PreparedStatement preparedStatement = null;
		PreparedStatement preparedStatement2 = null;
                if(jRadioButton1.isSelected()) 
                {
                String update = "update books set available=available+1 where id=1";
               //  String update2 = "update rent set date_f=1 where id_r=1";
                 
		try {
			dbConnection = getDBConnection();
			preparedStatement = dbConnection.prepareStatement(update);
                      // preparedStatement2 = dbConnection.prepareStatement(update2);
                        if(jTextField1.getText().length()==13 && contine_cifre(jTextField1.getText())==1)
                        { jLabel5.setText(null);
                            ResultSet rs = preparedStatement.executeQuery("SELECT * FROM rent where cnp_person="+jTextField1.getText());
                                      int cnp_exista = 0;
                                      
                                     
                     jLabel4.setText("<html>");
    while (rs.next()) {
        cnp_exista = 1;
        jLabel4.setForeground(Color.black);
         String date_f = rs.getString("date_f");
         String name_autor=rs.getString("name_autor");
         String name_book=rs.getString("name_book");
         System.out.println(name_book);
         if(rs.getString("cnp_person").equals(jTextField1.getText()))
             cnp_exista = 1;
         
         jLabel4.setText(jLabel4.getText()+i+")"+name_book+" ->"+name_autor);
         if(date_f==null)
         {
         jLabel4.setText(jLabel4.getText()+" (nereturnat)"+"<br>");
         }
         else
         {
             
             jLabel4.setText(jLabel4.getText()+" (returnat)"+"<br>");
         }
         i++;
     
       // else
     // System.out.println(name);
     // System.out.println(name);
    }
    jLabel4.setText(jLabel4.getText()+"</html>");
                  // jLabel4.setText("mue steaua");
      if(cnp_exista==0)
          jLabel5.setText("CNP inexistent");
      else jLabel5.setText(null);
                        }
                        else jLabel5.setText("CNP invalid");
    
   
                              
                        
                               
                          
                                
                        
                        
                        
                      //  preparedStatement2.setInt(2, valid);
                        
			                // System.out.println(existaUser);
                                         
                        
                 
            

		} catch (SQLException e) {

			System.out.println(e.getMessage());

		} finally {

			if (preparedStatement != null) {
                            try {
                                preparedStatement.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(cautare_carti.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}

			if (dbConnection != null) {
                            try {
                                dbConnection.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(cautare_carti.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}

		}
                }
                
                
                else if(jRadioButton2.isSelected()) 
                {
                    PreparedStatement preparedStatement1 = null;
		PreparedStatement preparedStatement3 = null;
                    String update = "update books set available=available+1 ";
               //  String update2 = "update rent set date_f=1 where id_r=1";
                 
		try {
			dbConnection = getDBConnection();
			preparedStatement1 = dbConnection.prepareStatement(update);
                      // preparedStatement2 = dbConnection.prepareStatement(update2);
                        jLabel5.setText(null);
                            ResultSet rs = preparedStatement1.executeQuery("SELECT * FROM person ");
                                      String name_exista=null;
                         while(rs.next())
                         {
                             String name = rs.getString("nume");
                          //   System.out.println("Nume de input : "+jTextField1.getText());
                           //  System.out.println("Nume baza de date : "+name);
                             if(name.equals(jTextField1.getText()))
                             {name_exista = rs.getString("cnp");
                                 
                             }
                         }
                       // System.out.println(name_exista);
                          if(name_exista==null)
                              jLabel5.setText("Persoana nu exista !");
                          else{
                        ResultSet rs1 = preparedStatement1.executeQuery("SELECT * FROM rent where cnp_person="+name_exista);
                        
                     jLabel4.setText("<html>");
    while (rs1.next()) {
        
        //jLabel4.setForeground(Color.black);
         String date_f = rs1.getString("date_f");
         String name_autor=rs1.getString("name_autor");
         String name_book=rs1.getString("name_book");
        
         
         jLabel4.setText(jLabel4.getText()+i+")"+name_book+" -> "+name_autor);
         if(date_f==null)
         {
         jLabel4.setText(jLabel4.getText()+" (nereturnat)"+"<br>");
         }
         else
         {
             
             jLabel4.setText(jLabel4.getText()+" (returnat)"+"<br>");
         }
         i++;
     
       // else
     // System.out.println(name);
     // System.out.println(name);
    }
                   
    
    jLabel4.setText(jLabel4.getText()+"</html>");
    
    
   }
                              
                        
                               
                          
                                
                        
                        
                        
                      //  preparedStatement2.setInt(2, valid);
                        
			                // System.out.println(existaUser);
                                         
                        
                 
            

		} catch (SQLException e) {

			System.out.println(e.getMessage());

		} finally {

			if (preparedStatement != null) {
                            try {
                                preparedStatement.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(cautare_carti.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}

			if (dbConnection != null) {
                            try {
                                dbConnection.close();
                            } catch (SQLException ex) {
                                Logger.getLogger(cautare_carti.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}

		}
                }
                    
                
                
                
                
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public int contine_cifre(String x)
{
    int i;
    for(i=0;i<x.length();i++)
        if(x.charAt(i)<'0' || x.charAt(i)>'9')
            return 0;
    return 1;
}
    private static Connection getDBConnection() {

		Connection dbConnection = null;

		try {

			Class.forName(DB_DRIVER);

		} catch (ClassNotFoundException e) {

			//System.out.println(e.getMessage());

		}

		try {

			dbConnection = DriverManager.getConnection(
                            DB_CONNECTION, DB_USER,DB_PASSWORD);
			return dbConnection;

		} catch (SQLException e) {

			System.out.println(e.getMessage());

		}

		return dbConnection;

	}

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())   
        {
            jRadioButton2.setSelected(false);
            jLabel5.setText(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected())   
        {
            jRadioButton1.setSelected(false);
            jLabel5.setText(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Inceput relationship = new Inceput();
        relationship.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cautare_carti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cautare_carti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cautare_carti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cautare_carti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cautare_carti().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
